#!/bin/bash
#PGG.SVpipeline.doccleaner.sh: A shell script used to delete temporary files generated by PGG.SVpipeline.sh
FLAG_INFILE=0

WD=`pwd`
#设定参数
if [ x$1 != x ]
then
	while getopts "i:s:" arg #选项后面的冒号表示该选项需要参数
	do
		case $arg in
		i)
			WD=$OPTARG
			;;
		s)
			TAG_INFILE=$OPTARG
			FLAG_INFILE=1
			;;
		?)  #当有不认识的选项的时候arg为?
			echo "FAIL: Unknown argument. Please check again."
			exit 1
			;;
		esac
	done
	
	until [ $FLAG_INFILE -eq 1 ]
	do
		echo "FAIL: no sampleID input!"
		exit 1
	done

	TIME=`date`
	echo ${TIME}
	echo "input file's location: ${WD}"
	echo "sample ID: ${TAG_INFILE}"
	echo "......"

	cd ${WD}
	if [ -e breakdancer/${TAG_INFILE} ] || [ -e breakseq2/${TAG_INFILE} ] || [ -e cnvnator/${TAG_INFILE} ] || [ -e lumpy/${TAG_INFILE} ] || [ -e pindel/${TAG_INFILE} ] || [ -e manta/${TAG_INFILE} ] || [ -e metasv//${TAG_INFILE} ]
	then
		#breakdancer
		if [ -e breakdancer/${TAG_INFILE} ]
		then
			rm -f breakdancer/${TAG_INFILE}/*size* 2>/dev/null
		fi

		#breakseq2
		if [ -e breakseq2/${TAG_INFILE} ]
		then
			rm -f breakseq2/${TAG_INFILE}/bplib* breakseq2/${TAG_INFILE}/final.bam breakseq2/${TAG_INFILE}/*.gff breakseq2/${TAG_INFILE}/*.out breakseq2/${TAG_INFILE}/*size* 2>/dev/null
		fi

		#lumpy
		if [ -e lumpy/${TAG_INFILE} ]
		then
			rm -f lumpy/${TAG_INFILE}/*bam lumpy/${TAG_INFILE}/*size* 2>/dev/null
		fi

		#pindel
		if [ -e pindel/${TAG_INFILE} ]
		then
			rm -f pindel/${TAG_INFILE}/*_BP 2>/dev/null
			rm -f pindel/${TAG_INFILE}/*_CloseEndMapped 2>/dev/null
			rm -f pindel/${TAG_INFILE}/*_D 2>/dev/null
			rm -f pindel/${TAG_INFILE}/*_INT_final 2>/dev/null
			rm -f pindel/${TAG_INFILE}/*_INV 2>/dev/null
			rm -f pindel/${TAG_INFILE}/*_LI 2>/dev/null
			rm -f pindel/${TAG_INFILE}/*.p2vlog 2>/dev/null
			rm -f pindel/${TAG_INFILE}/*_RP 2>/dev/null
			rm -f pindel/${TAG_INFILE}/*_SI 2>/dev/null
			rm -f pindel/${TAG_INFILE}/*_TD 2>/dev/null
			rm -f pindel/${TAG_INFILE}/*size* 2>/dev/null
			rm -r pindel/${TAG_INFILE}/*cfg 2>/dev/null
		fi
		
		#manta
		if [ -e manta/${TAG_INFILE} ]
		then
			rm -rf manta/${TAG_INFILE}/*.py manta/${TAG_INFILE}/*.txt manta/${TAG_INFILE}/*.pickle manta/${TAG_INFILE}/workspace manta/${TAG_INFILE}/results/evidence manta/${TAG_INFILE}/results/stats manta/${TAG_INFILE}/results/variants/*tbi manta/${TAG_INFILE}/results/variants/candidate* 2>/dev/null
		fi

		#metasv
		if [ -e metasv/${TAG_INFILE} ]
		then
			rm -rf metasv/${TAG_INFILE}/chr* 2>/dev/null
			rm -f metasv/${TAG_INFILE}/*err metasv/${TAG_INFILE}/*DEL.* metasv/${TAG_INFILE}/*.DUP* 2>/dev/null
		fi
	else
		echo "FAIL: no ${TAG_INFILE} output!"
		exit 1
	fi
	echo "Done!"

else
	echo "PGG.SVpipeline.doccleaner.sh: A shell script used to delete temporary files generated by PGG.SVpipeline.sh
	USAGE: PGG.SVpipeline.doccleaner.sh [-i ] [-s ]
	-i	location where you run PGG.SVpipeline.sh (=pwd if not declared)
	-s	sampleID
	example:PGG.SVpipeline.doccleaner.sh -s HGDP00711"
fi
